apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-actix-deployment
spec:
  selector:
    matchLabels:
      app: rust-actix
  replicas: 3
  template:
    metadata:
      labels:
        app: rust-actix
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - bencher
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: rust-actix
          image: BASE_DOCKER_REPO/kubench-rust-actix:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "900Mi"
              cpu: "2000m"
---
kind: Service
apiVersion: v1
metadata:
  name: rust-actix
spec:
  type: ClusterIP
  selector:
    app: rust-actix
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
