apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rust-dropshot-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rust-dropshot-deployment
  minReplicas: 3
  maxReplicas: 1000
  targetCPUUtilizationPercentage: 70
