apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-induzo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-induzo-deployment
  minReplicas: 3
  maxReplicas: 1000
  targetCPUUtilizationPercentage: 70
