name: Build and Push images
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: hub.docker.com    
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}   
      - uses: actions/checkout@v2
      - name: Build and push
        shell: bash        
        run: ./applications/build-n-push-all.sh vincentserpoul
